
spring.datasource.username=estudiantedes3
spring.datasource.password=desarrollo2026$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

admin.password=camilavuelve
usuario.password=aryquedate

jwt.secret=secureJwtSecretKeyForSpringFirstAppJWTImplementation
judge0.lenguajes=python,java,c++,kotlin,lua,perl,haskell,lisp,ruby,brainfuck,clojure,julia,assembly
judge0.api.url=https://judge0-ce.p.rapidapi.com
judge0.api.key=81d4fa7c91mshe54d0028749c6ffp1773dfjsn663bb43639d8
judge0.api.host=judge0-ce.p.rapidapi.com
judge0.lenguajes.ids=71,62,54,78,64,85,61,55,72,56,86,87,45

springdoc.swagger-ui.path=/
springdoc.swagger-ui.docExpansion=none
springdoc.swagger-ui.syntaxHighlight.activated=true
springdoc.swagger-ui.syntaxHighlight.theme=markdown
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.supportedSubmitMethods=get,post,put,delete
springdoc.swagger-ui.disable-swagger-default-url=true